swagger: '2.0'
info:
  version: '1.0'
  title: Abacus provisioning API description
  description: |
   A provisioning plugin provides REST APIs used by the Abacus usage processing pipeline to retrieve information about provisioned resources and the metering plans which should be used to meter their usage. For more
   details and examples, please have a look at the [resource provider guide](https://github.com/cloudfoundry-incubator/cf-abacus/blob/76dabd9ecc096ca8c8098eff0e2591ba2ed8f2f7/doc/resource-provider-guide.md#measure).

host: abacus-provisioning-plugin.<your_landscape_domain>.com
basePath: /v1/provisioning
schemes:
- https
produces:
- application/json
consumes:
- application/json
security:
  - systemToken:
    - abacus.usage.read
    - abacus.usage.write
paths:
  /metering/plans:
    post:
      summary: Creates resource provider metering plan.
      description: |
        This is an endpoint for creating a resource provider metering plans.
        For more details [MeteringPlan](https://github.com/cloudfoundry-incubator/cf-abacus/blob/76dabd9ecc096ca8c8098eff0e2591ba2ed8f2f7/doc/resource-provider-guide.md#metering-plan).
      parameters:
        - $ref: '#/parameters/meteringPlanBody'
      tags:
        - plans
      responses:
        201:
          description: Indicates successful create.
        409:
          description: Indicates the plan has a conflict.
  /metering/plan/{plan_id}:
    put:
      summary: Updates existing resource provider metering plan.
      description: |
        This is an endpoint for updating existing resource provider metering plan. It validates that the plan is already existing, otherwise returns proper status code.
        For more details [MeteringPlan](https://github.com/cloudfoundry-incubator/cf-abacus/blob/76dabd9ecc096ca8c8098eff0e2591ba2ed8f2f7/doc/resource-provider-guide.md#metering-plan).
      parameters:
        - $ref: '#/parameters/planId'
        - $ref: '#/parameters/meteringPlanBody'
      tags:
        - plans
      responses:
        200:
          description: Indicates successful update
        404:
          description: Indicates the plan is not found
  /pricing/plans:
    post:
      summary: Creates resource provider pricing plan.
      description: |
        This is an endpoint for creating resource provider pricing plans. For more details
        [PricingPlan](https://github.com/cloudfoundry-incubator/cf-abacus/blob/76dabd9ecc096ca8c8098eff0e2591ba2ed8f2f7/doc/resource-provider-guide.md#pricing-plan).
      parameters:
        - $ref: '#/parameters/pricingPlanBody'
      tags:
        - plans
      responses:
        201:
          description: Indicates successful create.
        409:
          description: Indicates the plan has a conflict.
  /pricing/plan/{plan_id}:
    put:
      summary: Updates existing resource provider pricing plan.
      description: |
       This is an endpoint for updating existing resource provider pricing plan. It validates that the plan is already existing, otherwise returns proper status code.
       For more details [PricingPlan](https://github.com/cloudfoundry-incubator/cf-abacus/blob/76dabd9ecc096ca8c8098eff0e2591ba2ed8f2f7/doc/resource-provider-guide.md#pricing-plan).
      parameters:
        - $ref: '#/parameters/planId'
        - $ref: '#/parameters/pricingPlanBody'
      tags:
        - plans
      responses:
        200:
          description: Indicates successful update
        404:
          description: Indicates the plan is not found
  /rating/plans:
    post:
      summary: Creates resource provider rating plan.
      description: |
        This is an endpoint for creating a resource provider rating plan.
        For more details [RatingPlan](https://github.com/cloudfoundry-incubator/cf-abacus/blob/76dabd9ecc096ca8c8098eff0e2591ba2ed8f2f7/doc/resource-provider-guide.md#rating-plan).
      parameters:
        - $ref: '#/parameters/ratingPlanBody'
      tags:
        - plans
      responses:
        201:
          description: Indicates successful create.
        409:
          description: Indicates the plan has a conflict.
  /rating/plan/{plan_id}:
    put:
      summary: Updates existing resource provider rating plan.
      description: |
        This is an endpoint for updating existing resource provider rating plan. It validates that the plan is already existing, otherwise returns proper status code.
        For more details [RatingPlan](https://github.com/cloudfoundry-incubator/cf-abacus/blob/76dabd9ecc096ca8c8098eff0e2591ba2ed8f2f7/doc/resource-provider-guide.md#rating-plan).
      parameters:
      - $ref: '#/parameters/planId'
      - $ref: '#/parameters/ratingPlanBody'
      tags:
        - plans
      responses:
        200:
          description: Indicates successful update
        404:
          description: Indicates the plan is not found
parameters:
  planId:
    name: plan_id
    in: path
    required: true
    type: string
    description: Resource provider plan identifier.
  pricingPlanBody:
    name: pricing_plan
    in: body
    required: true
    description: Resource provider pricing plan. JSON object that represents the plan based on PricingPlan model bellow.
    schema:
      $ref: '#/definitions/PricingPlan'
  ratingPlanBody:
    name: rating_plan
    description: Resource provider rating plan. JSON object that represents the plan based on RaingPlan model bellow.
    required: true
    in: body
    schema:
      $ref: '#/definitions/RatingPlan'
  meteringPlanBody:
    name: metering_plan
    in: body
    required: true
    description: Resource provider metering plan. JSON object that represents the plan based on MeteringPlan model bellow.
    schema:
      $ref: '#/definitions/MeteringPlan'

definitions:
  MeteringPlan:
    description: The metering plan defines the metering part of the calculations that Abacus will execute.
    properties:
      plan_id:
        description: Plan ID
        type: string
      measures:
       type: array
       items:
        $ref: '#/definitions/Measure'
      metrics:
        type: array
        items:
          $ref: '#/definitions/MeteringMetric'
  Measure:
   description: Measures are the raw data that you submit to Abacus. Each measure consists of multiple entries, each of them associated with a name and unit.
   properties:
    name:
     description: The name of the measure. For example `storage`, `heavy_api_calls` or `light_api_calls`.
     type: string
    unit:
     description: The unit of the measure. For example `BYTE` and `CALL`.
     type: string
  MeteringMetric:
    description: While the measures represent the raw data, the metrics combine and derive something out of the data.
    properties:
     name:
      description: The name of the metric. For example `storage` or `thousand_light_api_calls`.
      type: string
     unit:
      description: The unit of the metric. For example `GIGABYTE` and `THOUSAND_CALLS`.
      type: string
     type:
       description: There are two metric types `discrete` and `time-based`.
       type: string
       enum:
         - discrete
         - time-based
     meter:
       description: A map function responsible for transforming a raw measure into the unit used for metering.
       type: string
     accumulate:
       description: A reduce function responsible for accumulating metered usage over time.
       type: string
     aggregate:
       description: A reduce function responsible for aggregating usage in Cloud Foundry entities (space and organization), instead of time.
       type: string
     summarize:
       description: A reduce function responsible for summarizing the different types of usage.
       type: string
  PricingPlan:
    description: A pricing plan defines the pricing on per-measure basis.
    properties:
      plan_id:
        description: Plan ID
        type: string
      metrics:
        type: array
        items:
         $ref: '#/definitions/PricingMetric'
  PricingMetric:
    description: While the measures represent the raw data, the metrics combine and derive something out of the data.
    properties:
     name:
      description: The name of the metric. For example `storage` or `thousand_light_api_calls`.
      type: string
     prices:
      type: array
      items:
        $ref: '#/definitions/Price'
  Price:
    properties:
     country:
      description: The ID of the country. For example `EUR` or `USA`.
      type: string
     price:
      description: The price for the coresponding country.
      type: number
  RatingPlan:
    description: A rating plan defines the rating calculations.
    properties:
      plan_id:
        description: Plan ID
        type: string
      metrics:
        type: array
        items:
          $ref: '#/definitions/RatingMetric'
  RatingMetric:
    description: While the measures represent the raw data, the metrics combine and derive something out of the data.
    properties:
     name:
      description: The name of the metric. For example `storage` or `thousand_light_api_calls`.
      type: string
     rate:
       description: A simple map function responsible for converting an aggregated usage into a cost. This can be done at various levels like service instance, plan, app, space, org etc.
       type: string
     charge:
       description: A reduce function responsible for charging at various levels like service instance, plan, app, space, org and so on.
       type: string

securityDefinitions:
  systemToken:
    description: |
      The system token has scopes abacus.usage.read and abacus.usage.write.
      For more details [System Token](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/security.md#system-token).
    type: oauth2
    scopes:
      abacus.usage.read: Grants read access
      abacus.usage.write: Grants write access
    flow: accessCode
    authorizationUrl: https://login.cf.<your_landscape_domain>.com
    tokenUrl: https://uaa.cf.<your_landscape_domain>.com
